# .github/workflows/deploy.yml
name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install zappa
          pip install httplib2==0.22.0
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Update zappa_settings.json with environment variables
        run: |
          # Create a temporary file with environment variables replaced
          envsubst < zappa_settings.json > zappa_settings_tmp.json
          mv zappa_settings_tmp.json zappa_settings.json

      - name: Deploy to Lambda
        run: |
          source venv/bin/activate
          zappa update main || zappa deploy main
